# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
       - image: circleci/ruby:2.5.1-node-browsers
         environment:
           PGHOST: localhost
           PGUSER: test
           RAILS_ENV: test
           RACK_ENV: test
       - image: circleci/postgres:10.5-alpine-postgis-ram
         environment:
           POSTGRES_USER: test
           POSTGRES_DB: pets_local_test
           POSTGRES_PASSWORD: ""

    working_directory: ~/pets.local

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - restore_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run: bundle exec rails webpacker:install:vue
      - run: yarn add vue-turbolinks vue-resource

      - run:
          name: Set up Database
          command: |
            bundle exec rake db:create
            bundle exec rake db:schema:load
        environment:
           DATABASE_URL: postgresql://test@localhost:5432/pets_local_test

      # run tests!
      - run: bundle exec rails test
